plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.add(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
        }
        data {
            data()
            programArguments.addAll '--mod', mod_id, '--all',
                '--output', file('src/generated/resources/').absolutePath,
                '--existing', file('src/main/resources/').absolutePath
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven {
        url = "https://api.modrinth.com/maven"
    }
}

dependencies {
    //runtimeOnly("maven.modrinth:lhGA9TYQ:ZxYGwlk0")
    //runtimeOnly("maven.modrinth:1eAoo2KR:7TVdVtxF")
    //runtimeOnly("maven.modrinth:p19vrgc2:nipdgutM")
    //runtimeOnly("maven.modrinth:vEgtiJIY:p8G3gWwF")
    //runtimeOnly("maven.modrinth:RgWXq0La:fo9df0lp")
}
